// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upgjrglpphgzopiqwhhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZ2pyZ2xwcGhnem9waXF3aGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Nzk4MDAsImV4cCI6MjA2NTQ1NTgwMH0.SWvzBOGJl0XgGEc-mPgxViLDc3qLQ6oKgvaBNlBrz8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);